

const mayBeInterestedProducts_two = [

		{                              
	                 "image":     require('../images/viewProductDetails/mayBeInterestedProducts/2/1/1.jpg'),
                   "fullImage": require('../images/viewProductDetails/mayBeInterestedProducts/2/1/1.jpg'),
                   "imageGallery": [
                                 require('../images/viewProductDetails/mayBeInterestedProducts/2/1/1.jpg'),
                                 require('../images/viewProductDetails/mayBeInterestedProducts/2/1/2.jpg'),
                                 require('../images/viewProductDetails/mayBeInterestedProducts/2/1/3.jpg'),
                                 require('../images/viewProductDetails/mayBeInterestedProducts/2/1/4.jpg')
                                    ],
                   "title": 'HISENSE H43B7100UK 43" Smart 4K Ultra HD HDR LED TV',
                   "type": "TV",
                   "brand": "HISENSE",
                   "productCode": 510930,
                   "id": "MB1TV01",
                   "rating": 80,
                   "reviewsNumber": '5',
                   "description": "Picture quality: 1400 PQI\nHDR: HDR10 / Hybrid Log-Gamma (HLG)\nCatch-up TV & 4K streaming",
                   "oldPrice": undefined,
                   "price": 249.99,
                   "originalPrice": 249.99,
                   "diagonalSize": 43,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false, 
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "1400 PQI",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Samsung Smart Hub",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "SmartThings",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer, ITV Hub, All 4, My5, UKTV\n- Streaming: Netflix 4K, Prime Video 4K\n- Social media: YouTube\n- Full internet browser",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "1",
                            "AudioPower": "20w",
                            "SoundEnhancement": "Dolby Digital Plus",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Charcoal black",
                            "Material": "Aluminium & plastic",
                            "Height": "650.2",
                            "Width": "1125.8",
                            "DiagonalSize": 43,
                            "ProductWeight": "11.2kg",
                            "Guarantee": "1 year"
                          }]

        },
        {          "image":     require('../images/viewProductDetails/mayBeInterestedProducts/2/2/1.jpg'),
                   "fullImage": require('../images/viewProductDetails/mayBeInterestedProducts/2/2/1.jpg'),
                   "imageGallery": [
                                 require('../images/viewProductDetails/mayBeInterestedProducts/2/2/1.jpg'),
                                 require('../images/viewProductDetails/mayBeInterestedProducts/2/2/2.jpg'),
                                 require('../images/viewProductDetails/mayBeInterestedProducts/2/2/3.jpg'),
                                 require('../images/viewProductDetails/mayBeInterestedProducts/2/2/4.jpg')
                                    ],
                   "title": 'LOGIK L32SHE19 32" Smart HD Ready LED TV',
                   "type": "TV",
                   "brand": "LOGIK",
                   "productCode": 256495,
                   "id": "MB2TV02",
                   "rating": 75,
                   "reviewsNumber": '50',
                   "description": "Picture quality: 50 Hz\nCatch-up TV & streaming\nHDMI 1.4 x 2",
                   "oldPrice": undefined,
                   "price": 179.99,
                   "originalPrice": 179.99,
                   "diagonalSize": 32,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false, 
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "1400 PQI",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Samsung Smart Hub",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "SmartThings",
                            "OtherSmartFeatures": "Compatible with Samsung SmartThings devices.\nWorks with Amazon Alexa & Google Assistant",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "1",
                            "AudioPower": "20w",
                            "SoundEnhancement": "Dolby Digital Plus",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Charcoal black",
                            "Material": "Aluminium & plastic",
                            "Height": "650.2",
                            "Width": "1125.8",
                            "DiagonalSize": 32,
                            "ProductWeight": "13kg",
                            "Guarantee": "1 year"
                          }]


	        
        }
]

export default mayBeInterestedProducts_two;