

const tvProducts = [
				{
                    "image":     require('../images/product/tv/1/1.jpg'),
                    "fullImage": require('../images/product/tv/1/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/1/1.jpg'),
                                 require('../images/product/tv/1/2.jpg'),
                                 require('../images/product/tv/1/3.jpg'),
                                 require('../images/product/tv/1/4.jpg')
                                    ],
                   "title": 'SAMSUNG UE50RU7020KXXU 50" Smart 4K Ultra HD HDR LED TV',
                   "type": "TV",
                   "brand": "Samsung",
                   "productCode": 75256,
                   "id": "A1TV",
                   "rating": 80,
                   "reviewsNumber": '250',
                   "description": "Picture quality: 1400 PQI\nHDR: HDR10+ / Hybrid Log-Gamma (HLG)\nCatch-up TV & 4K streaming\nTV PLUS\nHDMI 2.0a x 3",
                   "oldPrice": undefined,
                   "price": 379.79,
                   "originalPrice": 379.79,
                   "diagonalSize": 55,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false, 
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "1400 PQI",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Samsung Smart Hub",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "SmartThings",
                            "OtherSmartFeatures": "Compatible with Samsung SmartThings devices.\nWorks with Amazon Alexa & Google Assistant",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "1",
                            "AudioPower": "20w",
                            "SoundEnhancement": "Dolby Digital Plus",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Charcoal black",
                            "Material": "Aluminium & plastic",
                            "Height": "650.2",
                            "Width": "1125.8",
                            "DiagonalSize": 55,
                            "ProductWeight": "13kg",
                            "Guarantee": "1 year"
                          }]
                   
   				 },
           {
                    "image":     require('../images/product/tv/2/1.jpg'),
                    "fullImage": require('../images/product/tv/2/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/2/1.jpg'),
                                 require('../images/product/tv/2/2.jpg'),
                                 require('../images/product/tv/2/3.jpg'),
                                 require('../images/product/tv/2/4.jpg')
                                    ],
                   "title": 'JVC LT-40CF890 Fire TV Edition 40" Smart 4K Ultra HD HDR LED TV',
                   "type": "TV",
                   "brand": "JVC",
                   "productCode": 266797,
                   "id": "A2TV",
                   "rating": 80,
                   "reviewsNumber": '3',
                   "description": "Picture quality: 50 Hz\nHDR: Dolby Vision / HDR10 / Hybrid Log-Gamma (HLG)\nCatch-up TV & 4K streaming\nFreeview HD\nHDMI 2.0b x 4",
                   "oldPrice": 329.99,
                   "price": 249.99,
                   "originalPrice": 249.99,
                   "diagonalSize": 40,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "1400 PQI",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Fire TV",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "SmartThings",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer, ITV Hub, All 4, My5, UKTV Play\n- Streaming: Prime Video 4K, Netflix 4K\nApp store: Amazon app store",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "1",
                            "AudioPower": "16w",
                            "SoundEnhancement": "Dolby Digital Plus",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Charcoal black",
                            "Material": "Aluminium & plastic",
                            "Height": "535",
                            "Width": "915",
                            "DiagonalSize": 40,
                            "ProductWeight": "6.05",
                            "Guarantee": "1 year"
                          }],
                   
           },
           {
                    "image":     require('../images/product/tv/3/1.jpg'),
                    "fullImage": require('../images/product/tv/3/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/3/1.jpg'),
                                 require('../images/product/tv/3/2.jpg'),
                                 require('../images/product/tv/3/3.jpg'),
                                 require('../images/product/tv/3/4.jpg')
                                    ],
                   "title": 'LG OLED55C9MLB 55" Smart 4K Ultra HD HDR OLED TV with Google Assistant',
                   "type": "TV",
                   "brand": "LG",
                   "productCode": 671081,
                   "id": "A3TV",
                   "rating": 85,
                   "reviewsNumber": '150',
                   "description": "2nd Gen α9 Processor for detailed images & custom sound\nThin OLED design\nHDR: Dolby Vision / HDR10 / Hybrid Log-Gamma (HLG)\nTCatch-up TV & 4K streaming\nFreeview HD with Freeview Play / Freesat HD",
                   "oldPrice": 989.99,
                   "price": 799.99,
                   "originalPrice": 799.99,
                   "diagonalSize": 55,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "2nd Gen α9 Intelligent Processor",
                            "DynConRatio": "Infinite",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Samsung Smart Hub",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "LG TV Remote",
                            "OtherSmartFeatures": "- Compatible with Apple AirPlay 2\n- Works with Google Assistant and Amazon Alexa speakers",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Bluetooth 5.0",
                            "Connections": "HDMI 2.1 x 4. USB 2.0 x 3",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "2",
                            "AudioPower": "40w",
                            "SoundEnhancement": "- Dolby Atmos, All Sount Tuning",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Charcoal black",
                            "Material": "Aluminium & plastic",
                            "Height": "706",
                            "Width": "46.9",
                            "DiagonalSize": 55,
                            "ProductWeight": "18.9kg",
                            "Guarantee": "5 year"
                          }],
                   
           },
           {
                    "image":     require('../images/product/tv/4/1.jpg'),
                    "fullImage": require('../images/product/tv/4/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/4/1.jpg'),
                                 require('../images/product/tv/4/2.jpg'),
                                 require('../images/product/tv/4/3.jpg'),
                                 require('../images/product/tv/4/4.jpg')
                                    ],
                   "title": 'SAMSUNG UE55RU7470UXXU 55" Smart 4K Ultra HD HDR LED TV with Bixby',
                   "type": "TV",
                   "brand": "SONY",
                   "productCode": 510232,
                   "id": "A4TV",
                   "rating": 90,
                   "reviewsNumber": '250',
                   "description": "Supreme UHD Dimming for improved contrast\nPicture quality: 2000 PQI\nHDR: HDR10+ / Hybrid Log-Gamma (HLG)\nTV PLUS / Freesat HD\nHDMI 2.0b x 3",
                   "oldPrice": undefined,
                   "price": 539.99,
                   "originalPrice": 539.99,
                   "diagonalSize": 55,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "2000 PQI",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "- Video CODEC: HEVC H.264 / VP9, - 4K upscaling picture enhancement",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Samsung Smart Hub",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "SmartThings",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer, ITV Hub, All 4, My5, UKTV Play\n- Streaming: Netflix 4K, Prime Video 4K, Rakuten 4K, Google Play 4K, NOW TV, CHILI, BT Sport, DisneyLife, BFI Player, BBC News, BBC Sport, hayu, Milkshake!, MUBI\n- App store: Samsung TV App Store\n Social media: YouTube 4K, Facebook Watch",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "1",
                            "AudioPower": "20w",
                            "SoundEnhancement": "Dolby Digital Plus",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Charcoal black",
                            "Material": "Aluminium & plastic",
                            "Height": "714",
                            "Width": "1225.8",
                            "DiagonalSize": 55,
                            "ProductWeight": "17.2kg",
                            "Guarantee": "1 year"
                          }],
                   
           },
           {
                    "image":     require('../images/product/tv/5/1.jpg'),
                    "fullImage": require('../images/product/tv/5/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/5/1.jpg'),
                                 require('../images/product/tv/5/2.jpg'),
                                 require('../images/product/tv/5/3.jpg'),
                                 require('../images/product/tv/5/4.jpg')
                                    ],
                   "title": 'PANASONIC TX-40GX700B 40" Smart 4K Ultra HD LED TV',
                   "type": "TV",
                   "brand": "PANASONIC",
                   "productCode": 264161,
                   "id": "A5TV",
                   "rating": 60,
                   "reviewsNumber": '71',
                   "description": "4K Studio Colour Processor for improved brightness & colour\nPicture quality: 1200 Hz BMR IFC\nHDR: HDR10+ / HDR10 / Hybrid Log-Gamma (HLG)\nCatch-up TV & 4K streaming\nFreeview HD with Freeview Play\nHDMI 2.0 x 3",
                   "oldPrice": 499.99,
                   "price": 379.99,
                   "originalPrice": 379.99,
                   "diagonalSize": 40,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "1200 Hz BMR IFC",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "My Home Screen 4.0",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "Philips TV remote app",
                            "OtherSmartFeatures": "Catch up TV: BBC iPlayer, ITV Hub, All 4, Demand 5\n- Streaming: Netflix 4K, Amazon Prime Video 4K, Rakuten TV, Chilli\n- Custom homepage\n- Full internet browser\n- Social media: YouTube 4K",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "- HDMI 2.0a x 3\n- Component input x 1\n- USB 3.0 x 1",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "2",
                            "AudioPower": "20w",
                            "SoundEnhancement": "Surround sound",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Charcoal black",
                            "Material": "Aluminium & plastic",
                            "Height": "517",
                            "Width": "901",
                            "DiagonalSize": 40,
                            "ProductWeight": "11kg",
                            "Guarantee": "2 year"
                          }],
                   
           },
           {
                    "image":     require('../images/product/tv/6/1.jpg'),
                    "fullImage": require('../images/product/tv/6/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/6/1.jpg'),
                                 require('../images/product/tv/6/2.jpg'),
                                 require('../images/product/tv/6/3.jpg'),
                                 require('../images/product/tv/6/4.jpg')
                                    ],
                   "title": 'PHILIPS 43PUS6554/12 43" Smart 4K Ultra HD HDR LED TV',
                   "type": "TV",
                   "brand": "PHILIPS",
                   "productCode": 510919,
                   "id": "A6TV",
                   "rating": 70,
                   "reviewsNumber": '250',
                   "description": "Picture quality: 1000 PPI\nPicture quality: 1200 Hz BMR IFC\nHDR: HDR10+ / HDR10 / Hybrid Log-Gamma (HLG)\nCatch-up TV & 4K streaming\nFreeview HD with Freeview Play\nHDMI 2.0 x 3",
                   "oldPrice": 329.99,
                   "price": 289.99,
                   "originalPrice": 289.99,
                   "diagonalSize": 43,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "1000 PPI",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Saphi Smart TV",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "Philips TV remote app",
                            "OtherSmartFeatures": "Catch up TV: BBC iPlayer, ITV Hub, All 4, Demand 5\nStreaming: Netflix 4K, Prime Video 4K\nApp store: Philips App Gallery\n- Custom homepage\n- Full internet browser\n- Social media: YouTube 4K",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "- HDMI 2.0a x 3\n- Component input x 1\n- USB 3.0 x 1",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "2",
                            "AudioPower": "20w",
                            "SoundEnhancement": "Surround sound",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Charcoal black",
                            "Material": "Aluminium & plastic",
                            "Height": "568",
                            "Width": "973",
                            "DiagonalSize": 43,
                            "ProductWeight": "8kg",
                            "Guarantee": "2 year"
                          }],
                   
           },
           {
                    "image":     require('../images/product/tv/7/1.jpg'),
                    "fullImage": require('../images/product/tv/7/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/7/1.jpg'),
                                 require('../images/product/tv/7/2.jpg'),
                                 require('../images/product/tv/7/3.jpg'),
                                 require('../images/product/tv/7/4.jpg')
                                    ],
                   "title": 'PHILIPS 32PFS5803/12 32" Smart Full HD LED TV',
                   "type": "TV",
                   "brand": "PHILIPS",
                   "productCode": 507302,
                   "id": "A7TV",
                   "rating": 65,
                   "reviewsNumber": '12',
                   "description": "Picture quality: 1400 PQI\nHDR: HDR10+ / Hybrid Log-Gamma (HLG)\nCatch-up TV & 4K streaming\nTV PLUS\nHDMI 2.0a x 3",
                   "oldPrice": undefined,
                   "price": 779.99,
                   "originalPrice": 779.99,
                   "diagonalSize": 32,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "1400 PQI",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Saphi Smart TV",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "Philips TV remote app",
                            "OtherSmartFeatures": "- Catch up TV: All 4, My5\n- Streaming: Netflix, Amazon Prime Video\n- App store: Philips app gallery\n- Full internet browser",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "1",
                            "AudioPower": "20w",
                            "SoundEnhancement": "DTS HD",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Black",
                            "Material": "Plastic",
                            "Height": "435",
                            "Width": "731",
                            "DiagonalSize": 32,
                            "ProductWeight": "4.5kg",
                            "Guarantee": "2 year"
                          }],
                   
           },
           {
                    "image":     require('../images/product/tv/8/1.jpg'),
                    "fullImage": require('../images/product/tv/8/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/8/1.jpg'),
                                 require('../images/product/tv/8/2.jpg'),
                                 require('../images/product/tv/8/3.jpg'),
                                 require('../images/product/tv/8/4.jpg')
                                    ],
                   "title": 'SONY BRAVIA KDL40WE663 40" Smart HDR LED TV',
                   "type": "TV",
                   "brand": "SONY",
                   "productCode": 194014,
                   "id": "A8TV",
                   "rating": 90,
                   "reviewsNumber": '20',
                   "description": "Full HD 1080p\nPicture quality: Motionflow XR 400 Hz\nCatch-up TV & Streaming\nFreeview HD\nHDMI x 2",
                   "oldPrice": undefined,
                   "price": 348.99,
                   "originalPrice": 348.99,
                   "diagonalSize": 40,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "Motionflow XR 400 Hz",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Vewd",
                            "ScreenMirroring": "Yes for iOS & Android",
                            "SmartphoneApp": "SmartThings",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer, ITV Hub, All 4, My5, UKTV Play\n- Streaming: Netflix, Prime Video\n- Custom homepage\n- Social media: YouTube",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "1",
                            "AudioPower": "10w",
                            "SoundEnhancement": "Dolby Digital Plus",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Charcoal black",
                            "Material": "Aluminium & plastic",
                            "Height": "543",
                            "Width": "910",
                            "DiagonalSize": 40,
                            "ProductWeight": "10.2kg",
                            "Guarantee": "1 year"
                          }],
                   
           },
           {
                    "image":     require('../images/product/tv/9/1.jpg'),
                    "fullImage": require('../images/product/tv/9/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/9/1.jpg'),
                                 require('../images/product/tv/9/2.jpg'),
                                 require('../images/product/tv/9/3.jpg'),
                                 require('../images/product/tv/9/4.jpg')
                                    ],
                   "title": 'SHARP 4T-C55BJ3KF2FB 55" Smart 4K Ultra HD HDR LED TV',
                   "type": "TV",
                   "brand": "SHARP",
                   "productCode": 714814,
                   "id": "A9TV",
                   "rating": 80,
                   "reviewsNumber": '9',
                   "description": "Picture quality: 1400 PQI\nHDR: HDR10+ / Hybrid Log-Gamma (HLG)\nCatch-up TV & 4K streaming\nTV PLUS\nHDMI 2.0a x 3",
                   "oldPrice": undefined,
                   "price": 329.99,
                   "originalPrice": 329.99,
                   "diagonalSize": 55,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "600 AMR",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "- Video CODEC: HEVC H.264 / VP9\n- 4K upscaling picture enhancement",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Aquos Net+",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "SmartThings",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer, ITV Hub, All 4, My5, UKTV Play\n- Streaming: Netflix 4K, Amazon Prime Video 4K\n- Social media: YouTube 4K",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "1",
                            "AudioPower": "20w",
                            "SoundEnhancement": "- Harmon Kardon\n- DTS Trusurround",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Charcoal black",
                            "Material": "Aluminium & plastic",
                            "Height": "723.4",
                            "Width": "1239.3",
                            "DiagonalSize": 55,
                            "ProductWeight": "13.8kg",
                            "Guarantee": "1 year"
                          }],
           },
           {
                    "image":     require('../images/product/tv/10/1.jpg'),
                    "fullImage": require('../images/product/tv/10/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/10/1.jpg'),
                                 require('../images/product/tv/10/2.jpg'),
                                 require('../images/product/tv/10/3.jpg'),
                                 require('../images/product/tv/10/4.jpg')
                                    ],
                   "title": 'PHILIPS 65OLED803/12 65" Smart 4K Ultra HD HDR OLED TV',
                   "type": "TV",
                   "brand": "PHILIPS",
                   "productCode": 252606,
                   "id": "A10TV",
                   "rating": 99,
                   "reviewsNumber": '9',
                   "description": "4K Ultra HD Premium Certified with HDR10+\nPicture quality: 4500 PPI\nCatch-up TV & 4K Streaming with Google Assistant\nTwin Freeview HD\nHDMI 2.0 x 2 / HDMI 1.4 x 2",
                   "oldPrice": undefined,
                   "price": 999.99,
                   "originalPrice": 999.99,
                   "diagonalSize": 65,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "4500 PPI",
                            "DynConRatio": "Mega",
                            "PicEnh": "P5 Perfect Picture Engine",
                            "Compatibility4K": "- Video CODEC: HEVC H.265 / VP9\n- 4K upscaling picture enhancement",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Android",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "Philips TV Remote",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer\n- Streaming: Netflix 4K, Prime Video 4K\n- App store: Google Play Store, Philips App Gallery\n- Full internet browser\n- Social media: Facebook video, YouTube\n- Gaming apps",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "4",
                            "AudioPower": "50w",
                            "SoundEnhancement": "DTS HD Premium Sound",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Silver",
                            "Material": "Metal",
                            "Height": "850.2",
                            "Width": "1449.8",
                            "DiagonalSize": 65,
                            "ProductWeight": "27.1kg",
                            "Guarantee": "2 year"
                          }],
                   
           },
           {
                    "image":     require('../images/product/tv/11/1.jpg'),
                    "fullImage": require('../images/product/tv/11/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/11/1.jpg'),
                                 require('../images/product/tv/11/2.jpg'),
                                 require('../images/product/tv/11/3.jpg'),
                                 require('../images/product/tv/11/4.jpg')
                                    ],
                   "title": 'LG 49SM8200PLA 49" Smart 4K Ultra HD HDR LED TV with Google Assistant ',
                   "type": "TV",
                   "brand": "LG",
                   "productCode": 264104,
                   "id": "A11TV",
                   "rating": 95,
                   "reviewsNumber": '17',
                   "description": "Picture quality: 1400 PQI\nHDR: HDR10+ / Hybrid Log-Gamma (HLG)\nCatch-up TV & 4K streaming\nTV PLUS\nHDMI 2.0a x 3",
                   "oldPrice": 699.99,
                   "price": 499.99,
                   "originalPrice": 499.99,
                   "diagonalSize": 49,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "TruMotion 100",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Samsung Smart Hub",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "SmartThings",
                            "OtherSmartFeatures": "NanoCell Technology for enhanced colour & wider viewing angles\nPicture quality: TruMotion 100\nHDR: HDR10 / Hybrid Log-Gamma (HLG)\nCatch-up TV & 4K streaming\nFreeview HD with Freeview Play / Freesat HD",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "1",
                            "AudioPower": "20w",
                            "SoundEnhancement": "Dolby Digital Plus",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Charcoal black",
                            "Material": "Metal & plastic",
                            "Height": "650.2",
                            "Width": "1125.8",
                            "DiagonalSize": 49,
                            "ProductWeight": "14kg",
                            "Guarantee": "5 year"
                          }],
                    
                   
           },
           {
                    "image":     require('../images/product/tv/12/1.jpg'),
                    "fullImage": require('../images/product/tv/12/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/12/1.jpg'),
                                 require('../images/product/tv/12/2.jpg'),
                                 require('../images/product/tv/12/3.jpg'),
                                 require('../images/product/tv/12/4.jpg')
                                    ],
                   "title": 'LOGIK L65UE18 65" Smart 4K Ultra HD HDR LED TV',
                   "type": "TV",
                   "brand": "LOGIK",
                   "productCode": 250469,
                   "id": "A12TV",
                   "rating": 85,
                   "reviewsNumber": '27',
                   "description": "4K Ultra HD with Dolby Vision\nPicture quality: 50 Hz\nCatch-up TV & 4K streaming\nFreeview HD with Freeview Play\nHDMI 2.0a x 3",
                   "oldPrice": undefined,
                   "price": 499.99,
                   "originalPrice": 499.99,
                   "diagonalSize": 65,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "TruMotion 100",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Logik Smart Platform",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "SmartThings",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer, ITV Hub, All 4, My5, UKTV \n- Streaming: Netflix 4K, Prime Video 4K\n- App store: Logik App Store\n- Full internet browser\n- Social media: Facebook, Twitter, YouTube",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "2",
                            "AudioPower": "20w",
                            "SoundEnhancement": "Dolby Digital Plus",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "91W",
                            "AnnualPowerConsum": "126 kWh",
                            "Colour": "Charcoal black",
                            "Material": "Plastic",
                            "Height": "841",
                            "Width": "1459.8",
                            "DiagonalSize": 65,
                            "ProductWeight": "23kg",
                            "Guarantee": "5 year"
                          }],
                    
                   
           },
           {
                    "image":     require('../images/product/tv/13/1.jpg'),
                    "fullImage": require('../images/product/tv/13/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/13/1.jpg'),
                                 require('../images/product/tv/13/2.jpg'),
                                 require('../images/product/tv/13/3.jpg'),
                                 require('../images/product/tv/13/4.jpg')
                                    ],
                   "title": 'TOSHIBA 40LL3A63DB 40" Smart Full HD LED TV',
                   "type": "TV",
                   "brand": "TOSHIBA",
                   "productCode": 501172,
                   "id": "A13TV",
                   "rating": 75,
                   "reviewsNumber": '7',
                   "description": "Picture quality: 50 Hz\nCatch-up TV & streaming\nFreeview HD with Freeview Play\nHDMI 1.4 x 3",
                   "oldPrice": 299.99,
                   "price": 248.99,
                   "originalPrice": 248.99,
                   "diagonalSize": 40,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "50 Hz",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Toshiba Smart",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "Toshthings",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer, ITV Hub, All 4, My5, UKTV \n- Streaming: Netflix 4K, Prime Video 4K\n- App store: Logik App Store\n- Full internet browser\n- Social media: Facebook, Twitter, YouTube",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "2",
                            "AudioPower": "20w",
                            "SoundEnhancement": "Dolby Digital Plus",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "71W",
                            "AnnualPowerConsum": "98 kWh",
                            "Colour": "Charcoal black",
                            "Material": "Plastic",
                            "Height": "534",
                            "Width": "916",
                            "DiagonalSize": 40,
                            "ProductWeight": "6kg",
                            "Guarantee": "1 year"
                          }],
                    
                   
           },
           {
                    "image":     require('../images/product/tv/14/1.jpg'),
                    "fullImage": require('../images/product/tv/14/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/14/1.jpg'),
                                 require('../images/product/tv/14/2.jpg'),
                                 require('../images/product/tv/14/3.jpg'),
                                 require('../images/product/tv/14/4.jpg')
                                    ],
                   "title": 'SAMSUNG UE32N5300AKXXU 32" Smart Full HD LED TV',
                   "type": "TV",
                   "brand": "SAMSUNG",
                   "productCode": 503811,
                   "id": "A14TV",
                   "rating": 65,
                   "reviewsNumber": '7',
                   "description": "Picture quality: 500 PQI\nCatch-up TV & streaming\nTV PLUS\nHDMI 1.4 x 3",
                   "oldPrice": undefined,
                   "price": 249.99,
                   "originalPrice": 249.99,
                   "diagonalSize": 32,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "500 PQI",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Samsung Smart App",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "SmartThings",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer, ITV Hub, All 4, My5\n- Streaming: Netflix, Amazon Prime Video, NOW TV, Rakuten, BT Sport\n- App store: Samsung TV App Store\n- Full internet browser\n- Social media: Facebook, YouTube",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "2",
                            "AudioPower": "20w",
                            "SoundEnhancement": "Dolby Digital Plus",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "41W",
                            "AnnualPowerConsum": "55 kWh",
                            "Colour": "Black",
                            "Material": "Plastic",
                            "Height": "438",
                            "Width": "734.5",
                            "DiagonalSize": 32,
                            "ProductWeight": "3.8kg",
                            "Guarantee": "1 year"
                          }],
                    
                   
           },
           {
                    "image":     require('../images/product/tv/15/1.jpg'),
                    "fullImage": require('../images/product/tv/15/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/15/1.jpg'),
                                 require('../images/product/tv/15/2.jpg'),
                                 require('../images/product/tv/15/3.jpg'),
                                 require('../images/product/tv/15/4.jpg')
                                    ],
                   "title": 'HISENSE H50B7100UK 50" Smart 4K Ultra HD HDR LED TV',
                   "type": "TV",
                   "brand": "HISENSE",
                   "productCode": 510943,
                   "id": "A15TV",
                   "rating": 50,
                   "reviewsNumber": '87',
                   "description": "Picture quality: 1500 PQI\nHDR: HDR10 / Hybrid Log-Gamma (HLG)\nCatch-up TV & 4K streaming\nFreeview HD with Freeview Play\nHDMI 2.0 x 3",
                   "oldPrice": 379.99,
                   "price": 299.99,
                   "originalPrice": 299.99,
                   "diagonalSize": 50,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "1500 PCI",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "-",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "-",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer, ITV Hub, All 4, My5\n- Streaming: Netflix, Amazon Prime Video, NOW TV, Rakuten, BT Sport\n- App store: Samsung TV App Store\n- Full internet browser\n- Social media: Facebook, YouTube",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "2",
                            "AudioPower": "7w",
                            "SoundEnhancement": "Dolby Digital Plus",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "41W",
                            "AnnualPowerConsum": "55 kWh",
                            "Colour": "Black",
                            "Material": "Plastic",
                            "Height": "656",
                            "Width": "1127",
                            "DiagonalSize": 50,
                            "ProductWeight": "9kg",
                            "Guarantee": "2 year"
                          }],
                    
                   
           },
           {
                    "image":     require('../images/product/tv/16/1.jpg'),
                    "fullImage": require('../images/product/tv/16/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/16/1.jpg'),
                                 require('../images/product/tv/16/2.jpg'),
                                 require('../images/product/tv/16/3.jpg'),
                                 require('../images/product/tv/16/4.jpg')
                                    ],
                   "title": 'JVC LT-40C591 40" Full HD LED TV - White',
                   "type": "TV",
                   "brand": "JVC",
                   "productCode": 255636,
                   "id": "A16TV",
                   "rating": 75,
                   "reviewsNumber": '82',
                   "description": "Picture quality: 60 Hz\nFreeview HD\nHDMI 1.4 x 3",
                   "oldPrice": undefined,
                   "price": 219.99,
                   "originalPrice": 219.99,
                   "diagonalSize": 40,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "60 Hz",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "-",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "-",
                            "OtherSmartFeatures": "-",
                            "Wifi": "None",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "2",
                            "AudioPower": "17w",
                            "SoundEnhancement": "DTS TruSurround",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "47W",
                            "AnnualPowerConsum": "67 kWh",
                            "Colour": "White",
                            "Material": "Plastic",
                            "Height": "517",
                            "Width": "901",
                            "DiagonalSize": 40,
                            "ProductWeight": "6.2kg",
                            "Guarantee": "1 year"
                          }],
                    
                   
           },
           {
                    "image":     require('../images/product/tv/17/1.jpg'),
                    "fullImage": require('../images/product/tv/17/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/17/1.jpg'),
                                 require('../images/product/tv/17/2.jpg'),
                                 require('../images/product/tv/17/3.jpg'),
                                 require('../images/product/tv/17/4.jpg')
                                    ],
                   "title": 'SONY BRAVIA KD65XG8096BU 65" Smart 4K Ultra HD HDR LED TV with Google Assistant',
                   "type": "TV",
                   "brand": "SONY",
                   "productCode": 264054,
                   "id": "A17TV",
                   "rating": 80,
                   "reviewsNumber": '122',
                   "description": "TRILUMINOS display for true-to-life colour\nPicture quality: Motionflow XR 400 Hz\nHDR: HDR10 / Hybrid Log-Gamma (HLG)\nFreeview HD with Freeview Play\nCatch-up TV & 4K streaming",
                   "oldPrice": 949.99,
                   "price": 799.99,
                   "originalPrice": 799.99,
                   "diagonalSize": 65,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "1500 PCI",
                            "DynConRatio": "Mega",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.264 / VP9",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Android TV",
                            "ScreenMirroring": "Chromecast",
                            "SmartphoneApp": "Video & TV Sideview: Remote app",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer, ITV Hub, All 4, My5\n- Streaming: Netflix, Amazon Prime Video, NOW TV, Rakuten, BT Sport\n- App store: Google Play Store\n- Full internet browser\n- Social media: Facebook, YouTube\n- Music: Spotify, Deezer, Tidal",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "2",
                            "AudioPower": "20w",
                            "SoundEnhancement": "Dolby Digital Plus",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "156W",
                            "AnnualPowerConsum": "216 kWh",
                            "Colour": "Black",
                            "Material": "Plastic",
                            "Height": "856",
                            "Width": "1427",
                            "DiagonalSize": 65,
                            "ProductWeight": "9kg",
                            "Guarantee": "2 year"
                          }],
                    
                   
           },
           {
                    "image":     require('../images/product/tv/18/1.jpg'),
                    "fullImage": require('../images/product/tv/18/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/18/1.jpg'),
                                 require('../images/product/tv/18/2.jpg'),
                                 require('../images/product/tv/18/3.jpg'),
                                 require('../images/product/tv/18/4.jpg')
                                    ],
                   "title": 'TOSHIBA 65U2963DB 65" Smart 4K Ultra HD HDR LED TV',
                   "type": "TV",
                   "brand": "TOSHIBA",
                   "productCode": 593167,
                   "id": "A18TV",
                   "rating": 96,
                   "reviewsNumber": '12',
                   "description": "Picture quality: 50 Hz\nHDR: Dolby Vision / HDR10\nCatch-up TV & 4K streaming\nFreeview HD with Freeview Play\nHDMI 2.0 x 3",
                   "oldPrice": undefined,
                   "price": 499.99,
                   "originalPrice": 499.99,
                   "diagonalSize": 65,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "50 Hz",
                            "DynConRatio": "20000:1",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.265 ",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "Toshiba Smart",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "Toshiba Smart Centre",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer, ITV Hub, All 4, My5\n- Streaming: Netflix, Amazon Prime Video, NOW TV, Rakuten, BT Sport\n- App store: Google Play Store\n- Full internet browser\n- Social media: Facebook, YouTube\n- Music: Spotify, Deezer, Tidal",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "2",
                            "AudioPower": "24w",
                            "SoundEnhancement": "Dolby Audio Processing",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "118W",
                            "AnnualPowerConsum": "172 kWh",
                            "Colour": "Black",
                            "Material": "Plastic",
                            "Height": "843",
                            "Width": "1462",
                            "DiagonalSize": 65,
                            "ProductWeight": "20kg",
                            "Guarantee": "1 year"
                          }],
                    
                   
           },
           {
                    "image":     require('../images/product/tv/19/1.jpg'),
                    "fullImage": require('../images/product/tv/19/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/19/1.jpg'),
                                 require('../images/product/tv/19/2.jpg'),
                                 require('../images/product/tv/19/3.jpg'),
                                 require('../images/product/tv/19/4.jpg')
                                    ],
                   "title": 'HISENSE H65U8BUK 65” Smart 4K Ultra HD HDR LED TV',
                   "type": "TV",
                   "brand": "HISENSE",
                   "productCode": 510932,
                   "id": "A19TV",
                   "rating": 96,
                   "reviewsNumber": '2',
                   "description": "Picture quality: 2800 PCI\nHDR: Dolby Vision / HDR10 / Hybrid Log-Gamma (HLG)\nCatch-up TV & 4K streaming\nFreeview HD with Freeview Play\nHDMI 2.0 x 4",
                   "oldPrice": 869.99,
                   "price": 799.99,
                   "originalPrice": 499.99,
                   "diagonalSize": 65,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "50 Hz",
                            "DynConRatio": "20000:1",
                            "PicEnh": "PurColour",
                            "Compatibility4K": "Video CODEC: HEVC H.265 ",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "VIDAA U 3.0",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "Hisense Remote Now",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer, ITV Hub, Demand 5, UKTV Player, CBS\n- Streaming: Netflix 4K, Prime Video 4\n- Custom homepage\n- Full internet browser\n- Social media: YouTube 4K",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "2",
                            "AudioPower": "15w",
                            "SoundEnhancement": "Dolby Atoms",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "118W",
                            "AnnualPowerConsum": "172 kWh",
                            "Colour": "Black & Silver",
                            "Material": "Plastic",
                            "Height": "842",
                            "Width": "1449",
                            "DiagonalSize": 65,
                            "ProductWeight": "26.8kg",
                            "Guarantee": "2 year"
                          }],
                    
                   
           },
           {
                    "image":     require('../images/product/tv/20/1.jpg'),
                    "fullImage": require('../images/product/tv/20/1.jpg'),
                    "imageGallery": [
                                 require('../images/product/tv/20/1.jpg'),
                                 require('../images/product/tv/20/2.jpg'),
                                 require('../images/product/tv/20/3.jpg'),
                                 require('../images/product/tv/20/4.jpg')
                                    ],
                   "title": 'LG 55UM7000PLC 55" Smart 4K Ultra HD HDR LED TV ',
                   "type": "TV",
                   "brand": "LG",
                   "productCode": 744593,
                   "id": "A20TV",
                   "rating": 20,
                   "reviewsNumber": '42',
                   "description": "Picture quality: 1600 PMI\nHDR: Dolby Vision / HDR10 / Hybrid Log-Gamma (HLG)\nCatch-up TV & 4K streaming\nFreeview HD with Freeview Play\nHDMI 2.0 x 4",
                   "oldPrice": 459.99,
                   "price": 399.99,
                   "originalPrice": 399.99,
                   "diagonalSize": 55,
                   "addedToCart": false,
                   "quantity": [1,2,3,4,5,6,7,8,9,10],
                   "selectedQuantity": 1,
                   "addedToCartLoading": false,
                   "removedFromCart": false,
                   "specs": [{
                            "ProcessRate": "1600 PMI",
                            "DynConRatio": "20000:1",
                            "PicEnh": "True Colour Accuracy",
                            "Compatibility4K": "Video CODEC: HEVC H.265 ",
                            "HDRGameMode": "Yes",
                            "NoiseReduction": "Yes",
                            "SmartPlatform": "webOS",
                            "ScreenMirroring": "Yes",
                            "SmartphoneApp": "LG Remote TV",
                            "OtherSmartFeatures": "- Catch up TV: BBC iPlayer, ITV Hub, Demand 5, UKTV Player, CBS\n- Streaming: Netflix 4K, Prime Video 4\n- Custom homepage\n- Full internet browser\n- Social media: YouTube 4K",
                            "Wifi": "Built-in WiFi",
                            "Ethernet": "Yes",
                            "Bluetooth": "Yes",
                            "Connections": "HDMI 2.0a x 3. USB 2.0 x",
                            "AudioOutput": "Optical x 1",
                            "Speakers": "2",
                            "AudioPower": "15w",
                            "SoundEnhancement": "Dolby Atoms",
                            "SupportsHigherResAudio": "Yes",
                            "EnergyEffClass": "A",
                            "OnModePowerConsum": "85w",
                            "AnnualPowerConsum": "118 kWh",
                            "Colour": "Black & Silver",
                            "Material": "Plastic",
                            "Height": "729",
                            "Width": "1247",
                            "DiagonalSize": 55,
                            "ProductWeight": "13.8kg",
                            "Guarantee": "1 year"
                          }],
                    
                   
           },
           



]

export default tvProducts;